### ISSUE TITLE
Composite by ojet serve placed in version folder

### ISSUE THREAD

**Issue by makker-nl** [geertjanw/ojet-training#3]
In step 2 of chapter 3, the following line is suggested to be added to the define block of the dashboard.js:
'jet-composites/my-employee-form/loader'.

This will result into an error loading the loader.js, because by _ojet serve,_ the component is copied to a version subfolder. (That is in ojet 5 at least):

![image](https://user-images.githubusercontent.com/20109787/44525496-62c91d80-a6e1-11e8-84a4-1e6e514809ba.png)

So in my case (ojet 5.2.0) it should be 'jet-composites/my-employee-form/1.0.0/loader'.

Same under (b), when reusing the cca component in incidents module.

**Comment by peppertech** [comment]
If you look at the main.js file in the /web folder, you'll see that the ojet tooling is doing a little magic for you now, starting in 5.2.0.  It adds a path config entry for any custom components that it finds under the /jet-composites folder.  It also adds a version directory based on the version in the components.json file.

All you need to add to your module define block now, is (using your example)  'my-employee-form/loader'  The actual path, with version number is handled behind the scenes as part of the path config.

In the /src folder, where you should be doing all of your work, nothing changes.  You will just see /jet-composites/my-employee-form/

**Comment by geertjanw** [comment]
Thanks, fixed the reference so that 'jet-composites' is not included and now it is only 'my-employee-form/loader'.
